### ISSUE TITLE
ValueError: Invalid reduction dimension 2 for input with 2 dimensions for translation model training after updating Ludwig 

### ISSUE THREAD

**Issue by farazk86** [ludwig-ai/ludwig#1130]
**Describe the bug**
Hi, 
I previously used Ludwig when it was using the ``Tensorflow1.x`` backend. And I created a machine translation project using it. But now after updating ludwig to the latest version, I can no longer run the same project. 

I am basically following the configuration mentioned in the example for translation: https://ludwig-ai.github.io/ludwig-docs/examples/#machine-translation

below is my ``model_definition.yaml``

```yaml
training:
    epochs: 500
    early_stop: 50
    batch_size: 128
#    dropout_rate: 0.3

input_features:
    -
        name: column1
        type: text
        level: word
        encoder: parallel_cnn
        representation: sparse      
        reduce_output: null
        preprocessing:
            word_tokenizer: space

output_features:
    -
        name: column2
        type: text
        level: word
        decoder: generator
        cell_type: lstm
        attention: bahdanau
        loss:
            type: sampled_softmax_cross_entropy
```

my terminal command:

```
ludwig train --experiment_name translate-1 --dataset training_file.csv --config_file model_definition.yaml --output_directory results
```
This is the error that is produced:

```
 ValueError: Invalid reduction dimension 2 for input with 2 dimensions. for '{{node ecd/text_output_feature/Max}} = Max[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=false](ecd/text_output_featu
re/Abs_1, ecd/text_output_feature/Max/reduction_indices)' with input shapes: [128,256], [] and with computed input tensors: input[1] = <2>.
```

Here are a few lines from the ``training_file.csv``

```
column1,column2
k k klk k hjkj hg k kg h k jlk k kj kg hk k k k k k k k klk kjh jkj hg ghk kj kh khgh hg,N S SHL S LHHL LL H SL H H LHL S SL HL HH S S S S S S S SHL SLL HHL LL SHH SL HL HLLH SL
hk lk kh klk l lmlk lml mn m klm mn m ml lj kl klk kjhj jh h h h klm l lm l l l l lk lmkl lkk hjh h h klk kj k klm mlkj kl ml lk lk m lk jkjh jh k k hkh hg hk lm kj gh hg hjk jh,NH HL SL HHL H SHLL HHL HH L LHH SH L SL SL HH LHL SLLH SL S S S HHH L SH L S S S SL HHLH SLS LHL S S HHL SL H SHH SLLL HH HL SL HL H LL LHLL HL H S LHL SL HH HH LL LH SL HHH LL
kj klkjkjh ghg hj j j jh jk hj ghjh hg g fg g g g hjhg hjh gf gh hkjklkjh hjhg hg,NL HHLLHLL LHL HH S S SL HH LH LHHL SL S LH S S S HHLL HHL LL HH SHLHHLLL SHLL HL
g j k l k h k k g g g k k kj g hk k kj h kj h g g,N H H H L L H S L S S H S SL L HH S SL L HL L L S
hkj k k k k kkk kh kl kmlkjk kj h hl l l lk kmlm jlkk j hl l l lk k k kmlm k k k kmlk k k k k kml k kkk hjkjhj jh jkl ljl lmlkj kjhg hg kk hk h kkkh jkl lmlk lkj,NHL H S S S SSS SL HH LHLLLH SL L SH S S SL SHLH LHLS L LH S S SL S S SHLH L S S SHLL S S S S SHL L SSS LHHLLH SL HHH SLH SHLLL HLLL HL HS LH L HSSL HHH SHLL HLL
e e e e de dcded edb cb dc de dc bcdc cb c ac c c bcdcb d dededc bc dcbc ba,N S S S LH LLHHL HLL HL HL HH LL LHHL SL H LH S S LHHLL H SHLHLL LH HLLH LL
g j k l l l k h l k j g h g f gh h k k jk h h g g,N H H H S S L L H L L L H L L HH S H S LH L S L S
f fedf d dfe fg g g ggf ed df ef d dhj h hgf g f efg fe de dd c ed d cd d df ghgfg e,N SLLH L SHL HH S S SSL LL SH LH L SHH L SLL H L LHH LL LH LS L HL S LH S SH HHLLH L
d fgh g g g g gh g g g ge g fgh fe dfc de fefed dc f ghg g gh g g gh g ghkjh jkjh g ghjhgh hg h gf g h kl kjkl lk h gf hkj klk kjh jh hg hg gh g g g fgh fe dfc de fefed g ghgf gh g ghkjh jkjh ghjhgh hg,N HHH L S S S SH L S S SL H LHH LL LHL HH HLHLL SL H HHL S SH L S SH L SHHLL HHLL L SHHLLH SL H LL H H HH LLHH SL L LL HHL HHL SLL HL SL HL SH L S S LHH LL LHL HH HLHLL H SHLL HH L SHHLL HHLL LHHLLH SL
```

**Environment (please complete the following information):**
 - OS: Windows 10
- Python version 3.6.8
- Ludwig version 0.33

**Comment by jimthompson5802** [comment]
@farazk86   thank you for submitting the issue.  With the information you provided, I was able to recreate the issue on my end.

**Comment by farazk86** [comment]
Hi, 

Thanks for verifying the bug. Is there any update on this? Is the problem related to Tensorflow 2? Would going to an earlier version of ludwig fix this?

**Comment by jimthompson5802** [comment]
@farazk86  re: the `sampled_softmax` issue.  We are still looking at it.   In the meantime, you should be able to use the regular softmax cross entropy loss function.

**Comment by farazk86** [comment]
> @farazk86 re: the `sampled_softmax` issue. We are still looking at it. In the meantime, you should be able to use the regular softmax cross entropy loss function.

I am still getting the same error with ``softmax_xross_entropy`` :(

below is my model file:

```yaml
training:
    epochs: 800
    early_stop: 60
    batch_size: 128
#    dropout_rate: 0.3

input_features:
    -
        name: nhl
        type: text
        level: word
        encoder: t5
        reduce_output: null
        trainable: true

output_features:
    -
        name: volpiano
        type: text
        level: word
        decoder: generator
        attention: bahdanau
        loss:
            type: softmax_cross_entropy
```

error:

```
 ValueError: Invalid reduction dimension 2 for input with 2 dimensions. for '{{node ecd/text_output_feature/Max}} = Max[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=false](ecd/text_output_featu
re/Abs_1, ecd/text_output_feature/Max/reduction_indices)' with input shapes: [128,512], [] and with computed input tensors: input[1] = <2>.
```

Please advise. :(

**Comment by jenishah** [comment]
Hi @jimthompson5802 , I admire this library and I would like to contribute.

I think https://github.com/ludwig-ai/ludwig/blob/9f03752c093949b6216f4a004549e0f0865fa442/ludwig/features/base_feature.py#L474

is causing the error. I tried by commenting out while keeping the loss type `softmax_cross_entropy` and it worked. I am not sure if that could have undesirable effects.

If you think I can work on this issue, please let me know.

**Comment by jimthompson5802** [comment]
@jenishah  thank you for the positive feedback on Ludwig.  

Re: the issue you are reporting.   Please provide a the `config.yaml` and a small dataset, if possible, to see if I can reproduce the error.

**Comment by farazk86** [comment]
> Hi @jimthompson5802 , I admire this library and I would like to contribute.
> 
> I think
> 
> https://github.com/ludwig-ai/ludwig/blob/9f03752c093949b6216f4a004549e0f0865fa442/ludwig/features/base_feature.py#L474
> 
> is causing the error. I tried by commenting out while keeping the loss type `softmax_cross_entropy` and it worked. I am not sure if that could have undesirable effects.
> 
> If you think I can work on this issue, please let me know.

Thanks for identifying the cause of this error :)

Did you find any effect of commenting this line out on your final result?

**Comment by jimthompson5802** [comment]
@farazk86  @jenishah I forgot to mention a PR was recently merged that fixed the `sampled_softmax` issue.  This fix will be in the next release of Ludwig.  In the meantime, if you want to see if the fix addresses this issue, just uninstall Ludwig and reinstall from Ludwig's main branch using this command:
```
pip install git+https://github.com/ludwig-ai/ludwig.git
```
Let me know if this helped or not.

**Comment by farazk86** [comment]
> @farazk86 @jenishah I forgot to mention a PR was recently merged that fixed the `sampled_softmax` issue. This fix will be in the next release of Ludwig. In the meantime, if you want to see if the fix addresses this issue, just uninstall Ludwig and reinstall from Ludwig's main branch using this command:
> 
> ```
> pip install git+https://github.com/ludwig-ai/ludwig.git
> ```
> 
> Let me know if this helped or not.

Hi Jim, 

Thanks for the reply. I was excited that the problem was resolved and uninstalled previous ludwig and installed from the above location as mentioned, but unfortunately I am getting the same error as before for the same dataset in my first post :(


```
 ValueError: Invalid reduction dimension 2 for input with 2 dimensions. for '{{node ecd/text_output_feature/Max}} = Max[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=false](ecd/text_output_featu
re/Abs_1, ecd/text_output_feature/Max/reduction_indices)' with input shapes: [128,512], [] and with computed input tensors: input[1] = <2>.
```

I tried with ``sampled_softmax_cross_entropy`` and ``softmax_cross_entropy``.

by installing from git link my ludwig version is : ``0.4.dev0``

**Comment by jimthompson5802** [comment]
@farazk86 thank you for the feedback.  Looks like there may be another subtle issue still left over from the latest PR.  Let me take a look at it.

**Comment by jenishah** [comment]
> > @farazk86 @jenishah I forgot to mention a PR was recently merged that fixed the `sampled_softmax` issue. This fix will be in the next release of Ludwig. In the meantime, if you want to see if the fix addresses this issue, just uninstall Ludwig and reinstall from Ludwig's main branch using this command:
> > ```
> > pip install git+https://github.com/ludwig-ai/ludwig.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know if this helped or not.
> 
> Hi Jim,
> 
> Thanks for the reply. I was excited that the problem was resolved and uninstalled previous ludwig and installed from the above location as mentioned, but unfortunately I am getting the same error as before for the same dataset in my first post :(
> 
> ```
>  ValueError: Invalid reduction dimension 2 for input with 2 dimensions. for '{{node ecd/text_output_feature/Max}} = Max[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=false](ecd/text_output_featu
> re/Abs_1, ecd/text_output_feature/Max/reduction_indices)' with input shapes: [128,512], [] and with computed input tensors: input[1] = <2>.
> ```
> 
> I tried with `sampled_softmax_cross_entropy` and `softmax_cross_entropy`.
> 
> by installing from git link my ludwig version is : `0.4.dev0`

I was able to run the code with that.. But I did not get chance to look deep enough and verify if it is safe to add flag to skip that part.

**Comment by farazk86** [comment]
> > > @farazk86 @jenishah I forgot to mention a PR was recently merged that fixed the `sampled_softmax` issue. This fix will be in the next release of Ludwig. In the meantime, if you want to see if the fix addresses this issue, just uninstall Ludwig and reinstall from Ludwig's main branch using this command:
> > > ```
> > > pip install git+https://github.com/ludwig-ai/ludwig.git
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Let me know if this helped or not.
> > 
> > 
> > Hi Jim,
> > Thanks for the reply. I was excited that the problem was resolved and uninstalled previous ludwig and installed from the above location as mentioned, but unfortunately I am getting the same error as before for the same dataset in my first post :(
> > ```
> >  ValueError: Invalid reduction dimension 2 for input with 2 dimensions. for '{{node ecd/text_output_feature/Max}} = Max[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=false](ecd/text_output_featu
> > re/Abs_1, ecd/text_output_feature/Max/reduction_indices)' with input shapes: [128,512], [] and with computed input tensors: input[1] = <2>.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried with `sampled_softmax_cross_entropy` and `softmax_cross_entropy`.
> > by installing from git link my ludwig version is : `0.4.dev0`
> 
> I was able to run the code with that.. But I did not get chance to look deep enough and verify if it is safe to add flag to skip that part.

Hi @jenishah did you manage to run the code with the line of code you refered to earlier commented out or did your installation of github run on my data without any modification to the code?

Thanks

**Comment by jenishah** [comment]
> > > > @farazk86 @jenishah I forgot to mention a PR was recently merged that fixed the `sampled_softmax` issue. This fix will be in the next release of Ludwig. In the meantime, if you want to see if the fix addresses this issue, just uninstall Ludwig and reinstall from Ludwig's main branch using this command:
> > > > ```
> > > > pip install git+https://github.com/ludwig-ai/ludwig.git
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Let me know if this helped or not.
> > > 
> > > 
> > > Hi Jim,
> > > Thanks for the reply. I was excited that the problem was resolved and uninstalled previous ludwig and installed from the above location as mentioned, but unfortunately I am getting the same error as before for the same dataset in my first post :(
> > > ```
> > >  ValueError: Invalid reduction dimension 2 for input with 2 dimensions. for '{{node ecd/text_output_feature/Max}} = Max[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=false](ecd/text_output_featu
> > > re/Abs_1, ecd/text_output_feature/Max/reduction_indices)' with input shapes: [128,512], [] and with computed input tensors: input[1] = <2>.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I tried with `sampled_softmax_cross_entropy` and `softmax_cross_entropy`.
> > > by installing from git link my ludwig version is : `0.4.dev0`
> > 
> > 
> > I was able to run the code with that.. But I did not get chance to look deep enough and verify if it is safe to add flag to skip that part.
> 
> Hi @jenishah did you manage to run the code with the line of code you refered to earlier commented out or did your installation of github run on my data without any modification to the code?
> 
> Thanks

I ran on your data, and you yaml file, but I commented out the line that I mentioned. Also, it worked only with `softmax_cross_entropy` loss

**Comment by Losbal** [comment]
> We are looking into this issue anyway, will update soon.

Have there been any updates on the reduce input error? I am also experiencing the same issue and receiving the same error reported above:

> ValueError: Invalid reduction dimension 2 for input with 2 dimensions. for '{{node ecd/text_output_feature/Max}} = Max[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=false](ecd/text_output_feature/Abs_1, ecd/text_output_feature/Max/reduction_indices)' with input shapes: [64,512], [] and with computed input tensors: input[1] = <2>.

Thanks in advance for your help!

**Comment by w4nderlust** [comment]
@Losbal just to confirm, this still happens in the latest release v0.4.1? What if you tried using the current master (v0.5-dev0)? We have done a big rework on master so it's very likely that the issue was solved as a side effect of it. If not @justinxzhao could potentially help.

**Comment by Losbal** [comment]
@w4nderlust Yes, I was using v0.4.1. I have installed v0.5 on a separate system as per your suggestion, and I haven't gotten the invalid reduction error from before, but now I am getting a different error:

>  Epoch  1
Training:   0% 0/422 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/net/fs01.cluster.com/home/losbal/venv/bin/ludwig", line 33, in <module>
    sys.exit(load_entry_point('ludwig', 'console_scripts', 'ludwig')())
  File "/net/fs01.cluster.com/home/losbal/Lud5/ludwig-master/ludwig/cli.py", line 164, in main
    CLI()
  File "/net/fs01.cluster.com/home/losbal/Lud5/ludwig-master/ludwig/cli.py", line 74, in __init__
    getattr(self, args.command)()
  File "/net/fs01.cluster.com/home/losbal/Lud5/ludwig-master/ludwig/cli.py", line 94, in experiment
    experiment.cli(sys.argv[2:])
  File "/net/fs01.cluster.com/home/losbal/Lud5/ludwig-master/ludwig/experiment.py", line 523, in cli
    experiment_cli(**vars(args))
  File "/net/fs01.cluster.com/home/losbal/Lud5/ludwig-master/ludwig/experiment.py", line 241, in experiment_cli
    debug=debug,
  File "/net/fs01.cluster.com/home/losbal/Lud5/ludwig-master/ludwig/api.py", line 1078, in experiment
    debug=debug,
  File "/net/fs01.cluster.com/home/losbal/Lud5/ludwig-master/ludwig/api.py", line 538, in train
    save_path=model_dir,
  File "/net/fs01.cluster.com/home/losbal/Lud5/ludwig-master/ludwig/models/trainer.py", line 751, in train
    self._train_loop(batcher, progress_tracker, save_path, train_summary_writer, progress_bar)
  File "/net/fs01.cluster.com/home/losbal/Lud5/ludwig-master/ludwig/models/trainer.py", line 941, in _train_loop
    targets,
  File "/net/fs01.cluster.com/home/losbal/Lud5/ludwig-master/ludwig/models/trainer.py", line 315, in train_step
    targets, model_outputs, self.regularization_type, self.regularization_lambda
  File "/net/fs01.cluster.com/home/losbal/Lud5/ludwig-master/ludwig/models/ecd.py", line 199, in train_loss
    train_loss += of_obj.loss["weight"] * of_train_loss
KeyError: 'weight'

I noticed that some of the acceptable parameter values have changed from v0.4 to v0.5; for example, softmax_cross_entropy is no longer accepted for text or sequence features, and so I had to change the loss type in my config file to sequence_softmax_cross_entropy for Ludwig to continue after receiving a different KeyError. But I'm not sure where this "weight" KeyError is originating.

I have included the parameters from my config file below:

training:
    validation_field: text_2
    validation_metric: loss
    early_stop: 10
    epochs: 50
    batch_size: 64
    learning_rate: 0.0003
    bucketing_field: text

preprocessing:
     text:
        word_tokenizer: english_tokenize
        word_sequence_length_limit: 25
        word_most_common: 50000
        padding_symbol: <PAD>
        unknown_symbol: <UNK>
        padding: right
        lowercase: false

input_features:
    -
        name: text
        type: text
        level: word
        encoder: transformer
        tied_weights: null
        representation: dense
        embedding_size: 300
        embeddings_trainable: true
        pretrained_embeddings: /home/losbal/embeds/GloveWikiCC6B/glove.6B.300d.txt
        embeddings_on_cpu: false
        num_layers: 6
        hidden_size: 512
        num_heads: 8
        transformer_fc_size: 512
        dropout: 0.2
        fc_layers: null
        num_fc_layers: 0
        fc_size: 512
        use_bias: true
        weights_initializer: zeros
        bias_initializer: zeros
        weights_regularizer: null
        bias_regularizer: null
        activity_regularizer: null
        norm: layer
        norm_params: null
        fc_activation: relu
        fc_dropout: 0.2
        reduce_output: null

output_features:
    -
        name: text_2
        type: text
        level: word
        decoder: generator
        reduce_input: sum
        dependencies: []
        reduce_dependencies: sum
        loss:
            type: sequence_softmax_cross_entropy
            confidence_penalty: 0
            robust_lambda: 0
            class_weights: 1
            class_similarities: null
            class_similarities_temperature: 0
            labels_smoothing: 0.1
            negative_samples: 0
            sampler: null
            distortion: 1
            unique: false
        fc_layers: null
        num_fc_layers: 0
        fc_size: 512
        use_bias: true
        weights_initializer: zeros
        bias_initializer: zeros
        norm: layer
        norm_params: null
        activation: relu
        dropout: 0.2
        cell_type: rnn
        state_size: 512
        attention: bahdanau
        attention_num_heads: 8
        embedding_size: 300
        beam_width: 12
        tied_embeddings: null

Any suggestions? Thanks again for your help!

**Comment by justinxzhao** [comment]
Thanks for the update @Losbal. Glad you aren't running into any errors on 0.5. Closing, though feel free to reopen if you run into any issues.

**Comment by w4nderlust** [comment]
@farazk86 @Losbal sorry it took so long to solve the issue, glad we managed to do it though! :)
